### ISSUE TITLE
iscroll in Android

### ISSUE THREAD

**Issue by db-murphy** [cubiq/iscroll#1000]
iscroll is a disaster in Android system; I think performance more important than function; alibaba company's anima-scroll is a better choose; link-> http://spmjs.io/package/anima-scroll; demo->http://m.taobao.com

**Comment by glebmachine** [comment]
It's ok, to use anima-scroll instead of iscroll.

But, if you wan't some constructive feedback, please provide descriptive demo. 

Most usual performance troubles occurs, when:
 - Complicated layers structure (huge recomposition on each frame)
 - Non gpu-accelerated properties animated instead of gpu-accelerated (top,left, instead of translate, translate3d)

Please, check your timeline in devtools first.
