### ISSUE TITLE
Twitter Bootstrap Tab with Iscroll 5 height issue

### ISSUE THREAD

**Issue by onlinerahul** [cubiq/iscroll#1006]
Hello,

I am facing issue with Iscroll with Twitter Bootstrap tab combination, you could refer to below live issue
http://codepen.io/onlinerahul/pen/KVQxPm

I am having two tabs:
1) Tab name "Home" having less content
2) Tab Name "Profile" having larger content 
Upon clicked on profile tab never shows full content.

I would appreciate it if you could reply at your earliest convenience.

Thanks
Rahul

**Comment by kaansoral** [comment]
bootstrap also uses js, you just don't see it

when you switch to profile, the height changes, so you have to refresh the iscroll at that point

http://codepen.io/anon/pen/jWZvbm - this works

the delay is because of the fade animation, if you disable the animation, it might work instantaneously

**Comment by onlinerahul** [comment]
Hi,

Thanks for the suggestion however if you are on "Profile" tab and then switched to "Home"
it keeps the same "profile" tab height in "home" tab as a results
shows unwanted height.

**Comment by kaansoral** [comment]
http://codepen.io/anon/pen/jWZvbm - here you go, added the .refresh routine to "Home" too

As a sincere suggestion to you, build from ground up, start with simple things, start from simple principles, don't use frameworks, things will be easier

Or just go ahead and use an all-in-one framework like ionic, where you can expect things to work for you, rather than making things work yourself

**Comment by onlinerahul** [comment]
Thanks, Dude! It works for me!
