### ISSUE TITLE
Android default browser fire two click event

### ISSUE THREAD

**Issue by ehretf** [cubiq/iscroll#361]
Hello,

I have noticed that the Android's default browser fire two click events on every DOM element when using iscroll with jquery and jquery mobile (no issue when using iscroll with jquery only).
This seems to be only with the default browser every thing is fine with Chrome (didn't test on other browser).
I noticed this issue with my Nexus 4 ( Android 4.2.2) and my Galaxy S (Cyanogen 9).

I have first thnik phonegap was the root cause but when using it on a web page (served by a remote http server) I had the same issue.

To fix this, I have changed click to vclick in line 558 in iscroll.js
ev.initMouseEvent('vclick', true, true, e.view ...

This seems to make iscroll acting fine and fixed my issue. This make iscroll depending on jquery and may need additionnal testing to ensure this doesn't break something else

I would like to know what you think on this and also this may help other users.

Thanks a lot

Best Regards.

Florent

**Comment by joantune** [comment]
Thank you for posting the issue and the solution. This was incredibly time consuming, especially because we didn't knew the problem came from iScroll, and we actually thought there was a Ghost click that the native WebView was triggering.

The fact that my android does not allow my chrome inspector to connect to the App's webview, didn't quite help ('old' version of Android [circa 4.2.x]).
Also, there's quite a lot of mambo jumbo out there that kinda confuses and doesn't help much.

So, a big +1

**Comment by sculove** [comment]
The event flow of android browser is different.
A little browser triggers mouse event before touch events.
Therefore, iScroll couldn't prevent next events.
so, click or tap event is fired twice over.

You can fix it if your browser is mobile.
`remove mouse events`
put disableMouse option to use in iScroll

```
new IScroll('#wrapper', {
     disableMouse : true,
     // ...
});
```

**Comment by zivester** [comment]
@sculove @cubiq - This was a pretty big breaking change which should have warranted a major version bump to `6.0.0`.  Changing the defaults pretty much breaks anyone (including my team) who is relying on them.  Thanks for the wonderful module, but hopefully next time this adheres to semver and only gets applied to the next major version bump.

**Comment by sculove** [comment]
@zivester The default values of disableMouse, disableTouch, disablePointer are decided automatically according to a browser.

eg1. if the browser is able to use pointer and touch and mouse events, iScroll options are like this.
```js
disablePointer: false,
disableTouch: true,
disableMouse: true
```
eg2. if the browser is able to use touch and mouse events, iScroll options are like this.
```js
disablePointer: true,
disableTouch: false,
disableMouse: true
```
eg3. if the browser is able to use mouse event, iScroll options are like this.
```js
disablePointer: true,
disableTouch: true,
disableMouse: false
```

I tested many devices.
Could you tell me what you are worrying about ?

**Comment by zivester** [comment]
@sculove 

Well the defaults changed which is 100% a breaking change.

We've tested this on numerous devices running chrome (Android 4, 5, iOS), of which we had declarations like the following:

```javascript
new Scroll($scrollWrapper, {
	mouseWheel: true,
	scrollbars: true,
	bounce: true,
	eventPassthrough: 'horizontal',
});
```

Touch events stopped being produced on these devices (and scrolling broke entirely), I'm assuming because of:

```
+		disableTouch : utils.hasPointer || !utils.hasTouch,
```

Locking our application into `5.1.3` resolves the issue.  I'd advise reverting this change on the `5.1.x` revision, and save the default upgrade to `6.x.x`.

**Comment by kaansoral** [comment]
No offense, but, every update to iscroll requires extensive testing and re-development due to the nature of the library

I tested 5.2.0 for example, it seemed extremely fast and smoother with speed, however, none of the clicks was working for me, probably because I had countless modifications to the code at 5.1.3, one of which perfected the android clicks for 5.1.3

What should definitely be tested are inputs, if input clicks doesn't work, it might break sign ups etc., my .02

**Comment by zivester** [comment]
I'm not debating whether the updates are meaningful, but the detection and defaults you introduced in this commit *do* break existing installations.

Do what you want with it, but we have locked into an older version while we make sure that our defaults are aligned to the pre `5.2.0` defaults.

I will fork this repo while removing the defaults introduced in this commit.  If you'll accept a PR for the removal of these defaults on the `5.x.x` revisions I will be happy to provide one.

**Comment by joantune** [comment]
If you are updating a library version without testing (or if you didn't
lock the version in the first place) do not complain that the update broke
your product. Never ship a new version without testing.

That said, this library is worse than making html+js for old versions of
I.E., because there are many different versions of the default webview for
Android, and a bit less for Apple's counterpart.
What I'm saying is: any little change can break anything anywhere, and
AFAIK there is no robust and free way to test in every platform (let me
know if there is).
Plus, never forget that this is an open source library, made out of
contributions, so an attitude like that really makes no sense for the
amount of contributions that you gave back.

**Comment by sculove** [comment]
@zivester I couldn't produce your situation.
I tested Chrome Desktop, Android 2,4,5, iOS8, 9.
Can you tell me your environment in detail?
- browser version, full iScroll options, or custom events...

**Comment by zivester** [comment]
@sculove:

```
navigator.userAgent
"Mozilla/5.0 (Linux; Android 5.1; XT1528 Build/LPI23.29-17.5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile Safari/537.36"
utils.hasPointer
true
utils.hasTouch
true
```

Obviously in this case, touch is being disabled because `hasPointer` is true.  I can reproduce this on all of my devices.  Would anything else trigger hasPointer being set to true for mobile chrome?

**Comment by sculove** [comment]
@zivester OK. 
I  added PEP before iScroll initialization. I face a problem on Chrome Desktop (Emulator), Android, iOS. 
but the Chrome Desktop is working.
That's as maybe this issue is PEP.
You'd better check PEP.

**Comment by hasbug** [comment]
i use iscroll5.2.0 ,set tap: true, but it still exists in android, there are two tap event fired.
