### ISSUE TITLE
Variable height on cells for infinite scroll setup

### ISSUE THREAD

**Issue by roundrobin** [cubiq/iscroll#911]
I tried to find a demo or documentation on how to create a infinite scroll list with variable height for the list items. 

Did anyone did something similar in the past? I couldn't find anything.

**Comment by davidpfahler** [comment]
I talked to @cubiq about this some time ago. He is already working on the next version of iscroll where this sort of thing would be possible. Because iscroll is a labor of love, we cannot consider adding feature to the current version of iscroll right now.

If you are interested in looking into this yourself: The trick is to rewrite the algorithm that takes existing cells and reuses them so that it can pool those cells into classes of heights (absolute variable height will not be possible / cause performance problems). It can then draw a cell from the right pool.

**Comment by roundrobin** [comment]
thanks for the response. I decided to go with the react-infinite library, because it does exactly what you describe above. 

I decided against iScroll because the current implementation for infinite scroll had almost no documentation and some of basic things like stop scrolling, loading indicators, reached end indicators are not supported.

**Comment by davidpfahler** [comment]
@roundrobin Thanks for your feedback, again. I understand your decision. Maybe a future version of iScroll will win you back :)
