### ISSUE TITLE
Chrome 44 Issues

### ISSUE THREAD

**Issue by tehmaestro** [cubiq/iscroll#943]
Hey. So it seems there are some issues with the latest Chrome, 44, on desktop. There's a weird effect when scrolling with iScroll. Anybody else having these issues?

**Comment by sculove** [comment]
The cause of this issue is BadAndroid conditional code.
iScroll determines the latest chrome(44) is bad android.

According to issue #760, #441, transitionDuration property is set to 0.001s in BadAndroid device.
Therefore, Slow sliding occurs on the latest Chrome or Android browsers

I propose workaround.
> 1. set `useTransition` to 'false'
   - if useTransition is false, iScroll use requestAnimationFrame to perform animations.
2. download following pull request 
  https://github.com/cubiq/iscroll/pull/949
  - a transtionDuration is set to 0.001 in `_transitionTime` method when 'useTransition' option is 'false'  
  - this PR is to avoid setting a transitionDuration property

**Comment by tehmaestro** [comment]
Thanks. Will test this tomorrow.

**Comment by tehmaestro** [comment]
The problem is not fixed. `useTransition` set to false decreases performance significantly and it is not a solution.
  I tried applying the changes from the commit, but there was no difference.

**Comment by sculove** [comment]
That's right. this solution is workaround.
BadAndroid conditional code is problem.
